# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Basic understanding
author: ''
email: ribosomatic@gmail.com
github_username: ribosomatic
description: >-
  An in-depth look at things of nature

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - .bundle/
  - vendor/

defaults:
  - scope:
      path: 'assets/images'
    values:
      image: true
